### ISSUE TITLE
System.DllNotFoundException on MacOS

### ISSUE THREAD

**Issue by pdf114514** [FabianFG/CUE4Parse#76]
How to solve?

CUE4Parse 1.0.4
Fortnite 23.20

Program.cs:
```cs
using System.IO;
using System.Text.Json;
using CUE4Parse.FileProvider;
using CUE4Parse.MappingsProvider;
using CUE4Parse.UE4.Versions;

var Provider = new DefaultFileProvider("PATH_TO_PAKS", SearchOption.TopDirectoryOnly, true, new(EGame.GAME_UE5_1));
Provider.MappingsContainer = new FileUsmapTypeMappingsProvider("PATH_TO_MAPPINGS");
Provider.Initialize();
Provider.SubmitKey(new(), new("0x8D69B1A2D9A71F8BAB2A7168E688F21484D88D219A8CE896715435518FB72916"));
Provider.LoadLocalization(ELanguage.English);

File.WriteAllText("./exported.json", JsonSerializer.Serialize(Provider.LoadObjectExports(null)));
```

Output:
```
Unhandled exception. System.DllNotFoundException: Unable to load shared library 'oo2core_9_win64.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: 
dlopen(/Volumes/mac/.dotnet/shared/Microsoft.NETCore.App/7.0.0/oo2core_9_win64.dll.dylib, 0x0001): tried: '/Volumes/mac/.dotnet/shared/Microsoft.NETCore.App/7.0.0/oo2core_9_win64.dll.dylib' (no such file), '/usr/local/lib/oo2core_9_win64.dll.dylib' (no such file), '/usr/lib/oo2core_9_win64.dll.dylib' (no such file)
dlopen(/Volumes/mac/Source/Repos/Test/bin/Debug/net7.0/oo2core_9_win64.dll.dylib, 0x0001): tried: '/Volumes/mac/Source/Repos/Test/bin/Debug/net7.0/oo2core_9_win64.dll.dylib' (no such file), '/usr/local/lib/oo2core_9_win64.dll.dylib' (no such file), '/usr/lib/oo2core_9_win64.dll.dylib' (no such file)
dlopen(oo2core_9_win64.dll.dylib, 0x0001): tried: 'oo2core_9_win64.dll.dylib' (no such file), '/usr/local/lib/oo2core_9_win64.dll.dylib' (no such file), '/usr/lib/oo2core_9_win64.dll.dylib' (no such file), '/Volumes/mac/Source/Repos/Test/oo2core_9_win64.dll.dylib' (no such file), '/usr/local/lib/oo2core_9_win64.dll.dylib' (no such file), '/usr/lib/oo2core_9_win64.dll.dylib' (no such file)
dlopen(/Volumes/mac/.dotnet/shared/Microsoft.NETCore.App/7.0.0/liboo2core_9_win64.dll.dylib, 0x0001): tried: '/Volumes/mac/.dotnet/shared/Microsoft.NETCore.App/7.0.0/liboo2core_9_win64.dll.dylib' (no such file), '/usr/local/lib/liboo2core_9_win64.dll.dylib' (no such file), '/usr/lib/liboo2core_9_win64.dll.dylib' (no such file)
dlopen(/Volumes/mac/Source/Repos/Test/bin/Debug/net7.0/liboo2core_9_win64.dll.dylib, 0x0001): tried: '/Volumes/mac/Source/Repos/Test/bin/Debug/net7.0/liboo2core_9_win64.dll.dylib' (no such file), '/usr/local/lib/liboo2core_9_win64.dll.dylib' (no such file), '/usr/lib/liboo2core_9_win64.dll.dylib' (no such file)
dlopen(liboo2core_9_win64.dll.dylib, 0x0001): tried: 'liboo2core_9_win64.dll.dylib' (no such file), '/usr/local/lib/liboo2core_9_win64.dll.dylib' (no such file), '/usr/lib/liboo2core_9_win64.dll.dylib' (no such file), '/Volumes/mac/Source/Repos/Test/liboo2core_9_win64.dll.dylib' (no such file), '/usr/local/lib/liboo2core_9_win64.dll.dylib' (no such file), '/usr/lib/liboo2core_9_win64.dll.dylib' (no such file)
dlopen(/Volumes/mac/.dotnet/shared/Microsoft.NETCore.App/7.0.0/oo2core_9_win64.dll, 0x0001): tried: '/Volumes/mac/.dotnet/shared/Microsoft.NETCore.App/7.0.0/oo2core_9_win64.dll' (no such file), '/usr/local/lib/oo2core_9_win64.dll' (not a mach-o file), '/usr/lib/oo2core_9_win64.dll' (no such file)
dlopen(/Volumes/mac/Source/Repos/Test/bin/Debug/net7.0/oo2core_9_win64.dll, 0x0001): tried: '/Volumes/mac/Source/Repos/Test/bin/Debug/net7.0/oo2core_9_win64.dll' (no such file), '/usr/local/lib/oo2core_9_win64.dll' (not a mach-o file), '/usr/lib/oo2core_9_win64.dll' (no such file)
dlopen(oo2core_9_win64.dll, 0x0001): tried: 'oo2core_9_win64.dll' (not a mach-o file), '/usr/local/lib/oo2core_9_win64.dll' (not a mach-o file), '/usr/lib/oo2core_9_win64.dll' (no such file), '/Volumes/mac/Source/Repos/Test/oo2core_9_win64.dll' (not a mach-o file), '/usr/local/lib/oo2core_9_win64.dll' (not a mach-o file), '/usr/lib/oo2core_9_win64.dll' (no such file)
dlopen(/Volumes/mac/.dotnet/shared/Microsoft.NETCore.App/7.0.0/liboo2core_9_win64.dll, 0x0001): tried: '/Volumes/mac/.dotnet/shared/Microsoft.NETCore.App/7.0.0/liboo2core_9_win64.dll' (no such file), '/usr/local/lib/liboo2core_9_win64.dll' (no such file), '/usr/lib/liboo2core_9_win64.dll' (no such file)
dlopen(/Volumes/mac/Source/Repos/Test/bin/Debug/net7.0/liboo2core_9_win64.dll, 0x0001): tried: '/Volumes/mac/Source/Repos/Test/bin/Debug/net7.0/liboo2core_9_win64.dll' (no such file), '/usr/local/lib/liboo2core_9_win64.dll' (no such file), '/usr/lib/liboo2core_9_win64.dll' (no such file)
dlopen(liboo2core_9_win64.dll, 0x0001): tried: 'liboo2core_9_win64.dll' (no such file), '/usr/local/lib/liboo2core_9_win64.dll' (no such file), '/usr/lib/liboo2core_9_win64.dll' (no such file), '/Volumes/mac/Source/Repos/Test/liboo2core_9_win64.dll' (no such file), '/usr/local/lib/liboo2core_9_win64.dll' (no such file), '/usr/lib/liboo2core_9_win64.dll' (no such file)

   at CUE4Parse.Compression.Oodle.OodleLZ_Decompress(Byte* buffer, Int64 bufferSize, Byte* output, Int64 outputBufferSize, Int32 a, Int32 b, Int32 c, Int64 d, Int64 e, Int64 f, Int64 g, Int64 h, Int64 i, Int32 threadModule)
   at CUE4Parse.Compression.Oodle.Decompress(Byte[] compressed, Int32 compressedOffset, Int32 compressedSize, Byte[] uncompressed, Int32 uncompressedOffset, Int32 uncompressedSize, FArchive reader)
   at CUE4Parse.MappingsProvider.Usmap.UsmapParser..ctor(FArchive archive)
   at CUE4Parse.MappingsProvider.Usmap.UsmapParser..ctor(Stream data, String name)
   at CUE4Parse.MappingsProvider.Usmap.UsmapParser..ctor(String path, String name)
   at CUE4Parse.MappingsProvider.UsmapTypeMappingsProvider.Load(String path)
   at CUE4Parse.MappingsProvider.FileUsmapTypeMappingsProvider..ctor(String path)
   at Program.<Main>$(String[] args) in /Volumes/mac/Source/Repos/Test/Program.cs:line 8
   ```

**Comment by GMatrixGames** [comment]
1) Fortnite is 5.2
2) You need the Oodle library, which we cannot provide. You must find that
on your own.

**Comment by pdf114514** [comment]
I found the Oodle and works well now
Thank you!
